### PR TITLE
Add sample Docker Compose script

### PR DESCRIPTION
**Pull request by flammable**
I hope this helps other people accomplish stuff like https://github.com/OliveTin/OliveTin/issues/89 too!

### CODE REVIEW

**Comment by flammable** [comment]
@jamesread hey, is this still something you're interested in documenting?

**Comment by jamesread** [comment]
Hey @flammable , sorry to leave you waiting, I've just had a busy few weeks. 

Thanks for taking the time to write the PR, I agree we need something here. 

I recently added the support for startup actions to OliveTin itself: 

---
actions: 
  - title: install stuff
    shell: microdnf install -y docker-compose
    execOnStartuo: true 
---

I think this is a cleaner solution, what do you think though?

**Comment by flammable** [comment]
Indeed, that's much cleaner! I don't think I had success with installing `docker compose` directly with `microdnf` though.

If I remember correctly, I think that's why I wrote the script to install `dnf` in that commented-out portion. That said, it was faster to just use `curl` to download `docker compose` and put it at the correct path, which is why that portion is not commented out.

`execOnStartup` is a much better solution, thanks!

**Comment by flammable** [comment]
Closing, since I switched this to `execOnStartup` in my own environment. Thanks!

**Pull request closed without merging**
