### PR TITLE
Speculatively add docs about how cron and acls should work together

### PR DESCRIPTION
**Pull request by sdahlbac**
This does not currently work due to a bug that is currently being investigating, but I am assuming that this is how it is supposed to work.

### CODE REVIEW

**Review by jamesread — APPROVED** [review]
Awesome, thanks so much!

**Comment by jamesread** [comment]
@sdahlbac , this looks like it has a merge conflict now - would you mind taking a look?

**Comment by sdahlbac** [comment]
@jamesread Would it have been merged in a timely manner this probably would not have happened... but oh well, I think I figured out where the cheese has been moved.

**Comment by jamesread** [comment]
Apologies @sdahlbac , sometimes life just gets in the way or maintaining projects. Accepted and merged now, thanks very much!

**Pull request merged**
